#include "Generator.hpp"
#include "MarkdownGenerator.hpp"
#include "ConsoleGenerator.hpp"
#include "JsonGenerator.hpp"

std::vector<Generator*> Generator::Generators{
	new MarkDownGenerator(),
	new ConsoleGenerator(),
	new JsonGenerator()
};


std::wstring Generator::GetTimeStr() {
	std::stringstream message;
	time_t time = std::time(nullptr);
	//tm localTime;
	//localtime_s(&localTime, &time);
	tm* localTime = localtime(&time);
	message << std::put_time(localTime, "%F %T%z");
	return StringUtil::s2ws(message.str());
}

std::wstring Generator::GetGenMessage() {
	return L"Auto-generated by TodoGen at " + Generator::GetTimeStr();
}